cat ./Ressources/Fonctions/pwd
cat ./Ressources/Blank
cat ./Ressources/Fonctions/mkdir
cat ./Ressources/Blank
cat ./Ressources/Fonctions/cd
cat ./Ressources/Blank
cat ./Ressources/Fonctions/ls
cat ./Ressources/Blank
cat ./Ressources/Fonctions/chmod
cat ./Ressources/Blank
cat ./Ressources/Fonctions/rm
cat ./Ressources/Blank
cat ./Ressources/Fonctions/cp
cat ./Ressources/Blank
cat ./Ressources/Fonctions/cat
cat ./Ressources/Blank
cat ./Ressources/Fonctions/mv
cat ./Ressources/Blank
cat ./Ressources/Fonctions/man
cat ./Ressources/Blank
cat ./Ressources/Fonctions/echo
cat ./Ressources/Blank
cat ./Ressources/Fonctions/sudo
