cat ./Ressources/Partie2
cat ./Ressources/Fonctions/pwd
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/mkdir
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/cd
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/ls
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/chmod
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/rm
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/cd
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/cp
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/mv
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/man
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/echo
read a
cat ./Ressources/Blank
cat ./Ressources/Fonctions/sudo
